"""add users table and relationship to receipts

Revision ID: 14f6fcfef558
Revises: 49299733f8a1
Create Date: 2026-02-28 02:20:35.773690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f6fcfef558'
down_revision: Union[str, None] = '49299733f8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=True)
    op.add_column('receipts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'receipts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'user_id')
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
