"""refactor: make image_path nullable for manual entries

Revision ID: 648dcc1b5264
Revises: 9e778ccb41e1
Create Date: 2026-03-03 02:18:51.358882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648dcc1b5264'
down_revision: Union[str, None] = '9e778ccb41e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
