"""add_currency_to_receipts

Revision ID: fe9ab81faaee
Revises: 52455c53c8c2
Create Date: 2026-03-17 18:35:50.202678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9ab81faaee'
down_revision: Union[str, None] = '52455c53c8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('currency', sa.String(), server_default='₪', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'currency')
    # ### end Alembic commands ###
